// Code generated by entc, DO NOT EDIT.

package stockmanager

const (
	// Label holds the string label denoting the stockmanager type in the database.
	Label = "stock_manager"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the stockmanager in the database.
	Table = "stock_managers"
)

// Columns holds all SQL columns for stockmanager fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
