// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// ContactParents is the predicate function for contactparents builders.
type ContactParents func(*sql.Selector)

// Form is the predicate function for form builders.
type Form func(*sql.Selector)

// StockManager is the predicate function for stockmanager builders.
type StockManager func(*sql.Selector)
