// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"dechild/ent/contactparents"
	"dechild/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContactParentsDelete is the builder for deleting a ContactParents entity.
type ContactParentsDelete struct {
	config
	hooks    []Hook
	mutation *ContactParentsMutation
}

// Where adds a new predicate to the ContactParentsDelete builder.
func (cpd *ContactParentsDelete) Where(ps ...predicate.ContactParents) *ContactParentsDelete {
	cpd.mutation.predicates = append(cpd.mutation.predicates, ps...)
	return cpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cpd *ContactParentsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cpd.hooks) == 0 {
		affected, err = cpd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ContactParentsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cpd.mutation = mutation
			affected, err = cpd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cpd.hooks) - 1; i >= 0; i-- {
			mut = cpd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cpd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpd *ContactParentsDelete) ExecX(ctx context.Context) int {
	n, err := cpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cpd *ContactParentsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: contactparents.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: contactparents.FieldID,
			},
		},
	}
	if ps := cpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cpd.driver, _spec)
}

// ContactParentsDeleteOne is the builder for deleting a single ContactParents entity.
type ContactParentsDeleteOne struct {
	cpd *ContactParentsDelete
}

// Exec executes the deletion query.
func (cpdo *ContactParentsDeleteOne) Exec(ctx context.Context) error {
	n, err := cpdo.cpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contactparents.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cpdo *ContactParentsDeleteOne) ExecX(ctx context.Context) {
	cpdo.cpd.ExecX(ctx)
}
