// Code generated by entc, DO NOT EDIT.

package ent

import (
	"dechild/ent/contactparents"
	"dechild/ent/form"
	"dechild/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactparentsFields := schema.ContactParents{}.Fields()
	_ = contactparentsFields
	// contactparentsDescID is the schema descriptor for id field.
	contactparentsDescID := contactparentsFields[0].Descriptor()
	// contactparents.IDValidator is a validator for the "id" field. It is called by the builders before save.
	contactparents.IDValidator = contactparentsDescID.Validators[0].(func(int) error)
	formFields := schema.Form{}.Fields()
	_ = formFields
	// formDescID is the schema descriptor for id field.
	formDescID := formFields[0].Descriptor()
	// form.IDValidator is a validator for the "id" field. It is called by the builders before save.
	form.IDValidator = formDescID.Validators[0].(func(int) error)
}
