// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"dechild/ent/stockmanager"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StockManagerCreate is the builder for creating a StockManager entity.
type StockManagerCreate struct {
	config
	mutation *StockManagerMutation
	hooks    []Hook
}

// Mutation returns the StockManagerMutation object of the builder.
func (smc *StockManagerCreate) Mutation() *StockManagerMutation {
	return smc.mutation
}

// Save creates the StockManager in the database.
func (smc *StockManagerCreate) Save(ctx context.Context) (*StockManager, error) {
	var (
		err  error
		node *StockManager
	)
	if len(smc.hooks) == 0 {
		if err = smc.check(); err != nil {
			return nil, err
		}
		node, err = smc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StockManagerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = smc.check(); err != nil {
				return nil, err
			}
			smc.mutation = mutation
			node, err = smc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(smc.hooks) - 1; i >= 0; i-- {
			mut = smc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, smc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (smc *StockManagerCreate) SaveX(ctx context.Context) *StockManager {
	v, err := smc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (smc *StockManagerCreate) check() error {
	return nil
}

func (smc *StockManagerCreate) sqlSave(ctx context.Context) (*StockManager, error) {
	_node, _spec := smc.createSpec()
	if err := sqlgraph.CreateNode(ctx, smc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (smc *StockManagerCreate) createSpec() (*StockManager, *sqlgraph.CreateSpec) {
	var (
		_node = &StockManager{config: smc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: stockmanager.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: stockmanager.FieldID,
			},
		}
	)
	return _node, _spec
}

// StockManagerCreateBulk is the builder for creating many StockManager entities in bulk.
type StockManagerCreateBulk struct {
	config
	builders []*StockManagerCreate
}

// Save creates the StockManager entities in the database.
func (smcb *StockManagerCreateBulk) Save(ctx context.Context) ([]*StockManager, error) {
	specs := make([]*sqlgraph.CreateSpec, len(smcb.builders))
	nodes := make([]*StockManager, len(smcb.builders))
	mutators := make([]Mutator, len(smcb.builders))
	for i := range smcb.builders {
		func(i int, root context.Context) {
			builder := smcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StockManagerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, smcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, smcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, smcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (smcb *StockManagerCreateBulk) SaveX(ctx context.Context) []*StockManager {
	v, err := smcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
