// Code generated by entc, DO NOT EDIT.

package ent

import (
	"dechild/ent/stockmanager"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// StockManager is the model entity for the StockManager schema.
type StockManager struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockManager) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockmanager.FieldID:
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type StockManager", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockManager fields.
func (sm *StockManager) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockmanager.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sm.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this StockManager.
// Note that you need to call StockManager.Unwrap() before calling this method if this StockManager
// was returned from a transaction, and the transaction was committed or rolled back.
func (sm *StockManager) Update() *StockManagerUpdateOne {
	return (&StockManagerClient{config: sm.config}).UpdateOne(sm)
}

// Unwrap unwraps the StockManager entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sm *StockManager) Unwrap() *StockManager {
	tx, ok := sm.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockManager is not a transactional entity")
	}
	sm.config.driver = tx.drv
	return sm
}

// String implements the fmt.Stringer.
func (sm *StockManager) String() string {
	var builder strings.Builder
	builder.WriteString("StockManager(")
	builder.WriteString(fmt.Sprintf("id=%v", sm.ID))
	builder.WriteByte(')')
	return builder.String()
}

// StockManagers is a parsable slice of StockManager.
type StockManagers []*StockManager

func (sm StockManagers) config(cfg config) {
	for _i := range sm {
		sm[_i].config = cfg
	}
}
